apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksbaranee-6094"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksbaranee-6094"
  template:
    metadata:
      labels:
        app: "aksbaranee-6094"
    spec:
      containers:
        - name: "aksbaranee-6094"
          image: "myown123.azurecr.io/aksbaranee"
          ports:
          - containerPort: 8080