on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n myown132 -g myown13297b8-rg --location "UK South" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n myown132 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n myown132 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n myown132 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: myown132.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myown132.azurecr.io/aks3:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myown132.azurecr.io/aks3:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_aks3_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myown132 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myown132`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myown132
        container-registry-url: myown132.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aks3dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myown132
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          myown132.azurecr.io/aks3:${{ github.sha }}
        imagepullsecrets: |
          aks3dockerauth   
